[workspace]
members = [
    "proto-dtls",
    "proto-grpc",
    "proto-http-1",
    "proto-http-2",
    "proto-http-3",
    "proto-ice",
    "proto-kafka",
    "proto-mqtt",
    "proto-quic",
    "proto-stun",
    "proto-tls",
    "proto-turn",
    "proto-upnp-igd-1",
    "proto-upnp-igd-2",
    "proto-webrtc",
]

[package]
name = "proto-tower"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["io-util", "time", "macros", "rt"] }

[dev-dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
