[workspace]
members = ["proto-http-2", "proto-http-1"]

[package]
name = "proto-tower"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["io-util", "time", "macros", "rt"] }

[dev-dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
