[package]
name = "proto-tower-kafka"
version = "0.1.4"
edition = "2021"
authors = [
    "RapidRecast <hugh@rapidrecast.io>",
]
description = "Tower implementation of the Kafka protocol"
license = "GPL-3.0-only"

[features]
data = []
client = ["data"]
server = ["data"]

[dependencies]
