[package]
name = "proto-h2c"
version = "0.1.0"
edition = "2021"

[dependencies]
tower = "0.5.2"
http = "1.2.0"
tokio = { version = "1.43.0", features = ["io-util", "time"] }
parser-helper = { git = "https://github.com/rapidrecast/parser-helper.git", branch = "main" }
proto-tower = { path = ".." }
