[package]
name = "proto-tower-turn"
version = "0.1.0"
edition = "2021"
authors = [
    "RapidRecast <hugh@rapidrecast.io>",
]
description = "Tower implementation of the TURN protocol"
license = "GPL-3"


[features]
data = []
client = ["data"]
server = ["data"]

[dependencies]
